CREATE TABLE IF NOT EXIST meal (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(128) NOT NULL,
rating FLOAT NOT NULL,

CONSTRAINT FK_restaurant
FOREIGN KEY (restaurant_id)
REFERENCES restaurant (id)
ON DELETE CASCADE
);